name = "cloudssh"
main = "src/worker/index.ts"
compatibility_date = "2026-06-16"
compatibility_flags = ["nodejs_compat"]
# no_bundle = true
workers_dev = false

[[routes]]
pattern = "ssh.goodfri.de5.net"
custom_domain = true

[[durable_objects.bindings]]
name = "SSH_SESSION"
class_name = "SSHSessionDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SSHSessionDO"]
